package raim;

import javax.swing.JFrame;

/**
 * The frame for the stand-alone application.
 *
 * @author Alex Laird
 * @author Ryan Morehart
 * @version 0.1
 */
public class RAIMFrame extends JFrame
{
    /** The panel that is added to the frame.*/
    private static RAIMPanel mainPanel;

    /**
     * Constructs the frame for the stand-alone application.
     */
    public RAIMFrame() throws RAIMException
    {
        mainPanel = new RAIMPanel(this);
        add(mainPanel);
        setLocation(50, 50);
        initComponents();
        mainPanel.connectToServer();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAIM 0.1");
        setName("mainFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    /**
     * The method responsible for constructing the visual frame and maintaining
     * the thread as long as the frame is open.
     *
     * @param args The command-line arguments.
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
				try
				{
					new RAIMFrame().setVisible(true);
				}
				catch(RAIMException ex)
				{
					System.out.println(ex.getMessage());
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}